# Generated by Django 4.0.2 on 2022-02-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('overview', models.TextField()),
                ('activities', models.TextField()),
                ('departure', models.DateField()),
                ('return_date', models.DateField()),
                ('included', models.TextField()),
                ('cancelation_policy', models.TextField()),
                ('additional_info', models.TextField()),
                ('posted', models.DateField(auto_now_add=True)),
                ('town', models.ManyToManyField(related_name='town', to='packages.Town')),
            ],
        ),
    ]
